import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { describeFaces } from '../api/_lib/faceRuntime';
import { descriptorDistance } from '../src/services/faceMatchMath';

// All paths must refer to authorized local photos. This script never uploads data.
// Labels must be assigned by the photographer, not generated by the matching model.
const manifestPath = process.argv[2];
if (!manifestPath) throw new Error('Usage: node --import tsx scripts/evaluate-face-matches.ts /absolute/labels.json');
const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
const root = path.dirname(path.resolve(manifestPath));
const cutoff = manifest.cutoff ?? 0.5;
if (!Number.isFinite(cutoff) || cutoff <= 0 || cutoff > 1) throw new Error('Invalid cutoff.');
if (!Array.isArray(manifest.cases) || !manifest.cases.some((c: any) => c.expected === true) ||
    !manifest.cases.some((c: any) => c.expected === false)) throw new Error('Both positive and negative labeled photos are required.');
const references = await describeFaces(await readFile(path.resolve(root, manifest.reference)));
const referenceIndex = manifest.referenceFaceIndex ?? 0;
if (!references[referenceIndex] || (references.length > 1 && manifest.referenceFaceIndex === undefined))
  throw new Error('Specify referenceFaceIndex for a group reference.');
const ref = references[referenceIndex];
let tp = 0, fp = 0, tn = 0, fn = 0, unreadable = 0, noFace = 0;
for (const c of manifest.cases) {
  if (typeof c.expected !== 'boolean' || typeof c.file !== 'string') throw new Error('Invalid case label.');
  try {
    const faces = await describeFaces(await readFile(path.resolve(root, c.file)));
    if (!faces.length) noFace++;
    const distance = Math.min(...faces.map(face => descriptorDistance(ref, face)));
    const predicted = distance <= cutoff;
    if (predicted && c.expected) tp++;
    else if (predicted) fp++;
    else if (c.expected) fn++;
    else tn++;
    console.log(JSON.stringify({ file: c.file, expected: c.expected, predicted, faceCount: faces.length,
      distance: Number.isFinite(distance) ? Number(distance.toFixed(4)) : null }));
  } catch { unreadable++; console.log(JSON.stringify({ file: c.file, error: 'UNREADABLE_OR_INFERENCE_FAILED' })); }
}
console.log(JSON.stringify({ cutoff, truePositive: tp, falsePositive: fp, trueNegative: tn, falseNegative: fn,
  unreadable, noFace, precision: tp + fp ? tp / (tp + fp) : null, recall: tp + fn ? tp / (tp + fn) : null }));
// A release gate requires every labeled positive to be found and no negative returned.
// Passing a small fixture set still does not establish production accuracy.
if (fp || fn || unreadable) process.exitCode = 1;
